version: '3'
services:
  springbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./voice_messages:/app/voice_messages
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/currency_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json # Add this line to specify the path to the JSON key file
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=currency_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
